[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/spots"
  to = "/.netlify/functions/spots"
  status = 200

[[redirects]]
  from = "/api/spot"
  to = "/.netlify/functions/spot"
  status = 200

[[redirects]]
  from = "/api/place-hours"
  to = "/.netlify/functions/place-hours"
  status = 200

[[redirects]]
  from = "/api/walking-distance"
  to = "/.netlify/functions/walking-distance"
  status = 200
