-- KaaiSpots — Supabase/PostgreSQL schema
-- Voer dit uit in de Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql

CREATE TABLE IF NOT EXISTS spots (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  lat          DOUBLE PRECISION NOT NULL,
  lng          DOUBLE PRECISION NOT NULL,
  walk         INTEGER NOT NULL,
  bike         INTEGER,
  transit      INTEGER,
  address      TEXT,
  phone        TEXT,
  website      TEXT,
  price        INTEGER NOT NULL DEFAULT 0,
  color        TEXT NOT NULL,
  favorite     BOOLEAN DEFAULT FALSE,
  cats         TEXT[] NOT NULL DEFAULT '{}',
  short_desc   TEXT,
  long_desc    TEXT,
  tips         TEXT,
  student_perk TEXT,
  why          TEXT[],
  payments     TEXT[] DEFAULT '{}',
  hours        JSONB,
  menu         JSONB,
  facilities   JSONB
);

-- Publieke read-only toegang via Row Level Security
ALTER TABLE spots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON spots FOR SELECT USING (true);

-- ============================================================
-- Seed data — alle 17 spots
-- ============================================================

INSERT INTO spots (id, name, lat, lng, walk, bike, transit, address, phone, website, price, color, favorite, cats, short_desc, long_desc, tips, student_perk, why, payments, hours, menu, facilities) VALUES

('castelao', 'Établissement Castelao',
 50.84009017991707, 4.3258508412449075,
 4, NULL, NULL,
 'Bergensesteenweg 258, 1070 Anderlecht', '025220341', NULL,
 1, '#FF6B35', TRUE,
 ARRAY['Eten'],
 'Onze vaste broodjeszaak. Belegde baguette, vriendelijke bazin, geen poespas.',
 'Een tegelvloer uit 1962, een toonbank vol charcuterie en madame Castelao die elke student bij naam kent. Studentenkorting (-10%) op vertoon van je EhB-kaart, en als je vraagt om "den dagschotel" geeft ze meestal iets dat niet op de kaart staat.',
 'Donderdag is dagschotel-dag (lasagne). Ga vroeg, om 12u30 staat er rij.',
 '−10% op vertoon van EhB-kaart',
 ARRAY['Goedkoopste warme lunch in straal van 500m','Studentenkorting met EhB-kaart','4 min wandelen vanaf de campus','Wifi vragen mag, maar werkt traag'],
 ARRAY['Cash','Bancontact','Payconiq'],
 '{"Zondag":"Gesloten","Maandag":"10:00 – 15:30","Dinsdag":"10:00 – 15:30","Woensdag":"10:00 – 15:30","Donderdag":"10:00 – 15:30","Vrijdag":"10:00 – 15:30","Zaterdag":"Gesloten"}'::jsonb,
 '[{"section":"Belegde broodjes","items":[{"name":"Boterham Boerenham","desc":"Hesp, augurkjes, mosterd","price":"3,50"},{"name":"Baguette Italien","desc":"Salami, mozzarella, tomaat, pesto","price":"5,80"},{"name":"Vegabroodje","desc":"Hummus, geroosterde paprika, rucola","price":"5,20"},{"name":"Croque Castelao","desc":"Huisspecialiteit — kaas, hesp, bechamel","price":"6,50"}]},{"section":"Warm","items":[{"name":"Soep van de dag","desc":"Met stuk brood","price":"3,00"},{"name":"Spaghetti bolognaise","desc":"Familierecept","price":"7,50"},{"name":"Dagschotel","desc":"Wisselt — vraag aan de toog","price":"8,90"}]},{"section":"Drank","items":[{"name":"Koffie","desc":"Klein / groot","price":"1,80 / 2,40"},{"name":"Verse jus","desc":"Sinaas, geperst per glas","price":"3,50"},{"name":"Pintje","desc":"Jupiler, na 11u","price":"2,80"}]}]'::jsonb,
 NULL),

('kafka', 'Café Kafka',
 50.84927761999179, 4.3480804,
 6, NULL, NULL,
 'Rue des Poissonniers 21, 1070 Anderlecht', NULL, 'https://kaffabar.be',
 1, '#4A2FAB', FALSE,
 ARRAY['Drinken','Studeren'],
 'Brak lichtinval, sterke koffie, stopcontacten op elke tafel. Stilteplek tot 17u.',
 'Voormalig boekenwinkeltje omgebouwd tot café. De achterzaal is officieel "stiltezone" tot 17u — laptops welkom, telefoongesprekken niet. Na 17u draait de muziek aan en wordt het een gewoon buurtcafé.',
 'Ga naar de achterzaal voor stilte. Vrijdagavond is er soms vinyl-DJ.',
 'Eerste koffie gratis bij eerste bezoek — vraag ernaar',
 ARRAY['Stopcontact bij elke tafel','Wifi-paswoord op het bord (KAFKA2026)','Koffie blijft 1,80 — al jaren','Achterzaal is stil tot 17u'],
 ARRAY['Cash','Bancontact'],
 '{"Maandag":"08:00 – 22:00","Dinsdag":"08:00 – 22:00","Woensdag":"08:00 – 22:00","Donderdag":"08:00 – 23:00","Vrijdag":"08:00 – 00:00","Zaterdag":"10:00 – 00:00","Zondag":"10:00 – 20:00"}'::jsonb,
 '[{"section":"Koffie & thee","items":[{"name":"Espresso","desc":"","price":"1,80"},{"name":"Cappuccino","desc":"Met of zonder cacao","price":"2,80"},{"name":"Flat white","desc":"Bonen van Or Coffee","price":"3,20"},{"name":"Verse muntthee","desc":"Met honing","price":"3,00"}]},{"section":"Bier op tap","items":[{"name":"Jupiler","desc":"25cl","price":"2,80"},{"name":"Karmeliet Tripel","desc":"33cl","price":"4,50"},{"name":"Brussels Calling","desc":"Lokaal, IPA","price":"4,80"}]},{"section":"Klein eten","items":[{"name":"Toast kaas/hesp","desc":"","price":"4,50"},{"name":"Bord olijven & brood","desc":"","price":"5,50"},{"name":"Charcuterie plank","desc":"Voor 2","price":"12,00"}]}]'::jsonb,
 NULL),

('parkvorst', 'Park van Vorst',
 50.8252, 4.3278,
 12, NULL, NULL,
 'Park van Vorst, 1190 Vorst', NULL, NULL,
 0, '#1F6B2E', FALSE,
 ARRAY['Chillen','Gratis'],
 'Open grasveld, vijver, weinig toeristen. Perfect voor een lange middagpauze.',
 'Een van de weinige Brusselse parken waar je nog gewoon op het gras mag liggen zonder dat een agent komt zeggen dat het verboden is. Vijver met eenden, een tiental beuken die schaduw geven, en in de zomer wordt er soms gratis film geprojecteerd op een opblaasbaar scherm.',
 'In juli/augustus elke donderdagavond gratis openluchtcinema (vanaf 21u30).',
 NULL,
 ARRAY['Helemaal gratis','Geen toeristen','Bankjes met rugleuning (zeldzaam)','Drinkfontein bij de hoofdingang'],
 ARRAY[]::text[],
 '{"Alle dagen":"Open 24/7 (verlicht tot 22u)"}'::jsonb,
 NULL,
 '[{"name":"Drinkfontein","desc":"Bij hoofdingang"},{"name":"Toiletten","desc":"Gratis, geopend 9–17u"},{"name":"Speelplein","desc":"In het zuidelijke deel"},{"name":"Boules-pleintje","desc":"Materiaal moet je zelf meebrengen"}]'::jsonb),

('abattoir', 'Abattoir Markt',
 50.84321248872317, 4.325844886000292,
 8, NULL, NULL,
 'Ropsy Chaudronstraat 24, 1070 Anderlecht', NULL, NULL,
 1, '#B5430A', FALSE,
 ARRAY['Eten','Cultuur'],
 'Vrijdag-zaterdag-zondag. Goedkope groenten, Marokkaanse bakkers, levendig.',
 'De grootste overdekte markt van Brussel, op het terrein van een oud slachthuis. Ongeveer 150 kraampjes: groenten, vis, kruiden, stoffen, goedkope kleren, vers brood. Kom hier niet voor tafel-ervaring — kom om eten mee te nemen of een msemmen-pannenkoek voor 1,50 ter plaatse op te eten.',
 'Kom voor 11u, dan is alles vers en nog niet uitverkocht. Neem een eigen tas mee.',
 NULL,
 ARRAY['Groenten 30% goedkoper dan supermarkt','Verse Marokkaanse bakkers','Echt Brussel, geen toeristenmarkt','Open op zondag (zeldzaam)'],
 ARRAY['Vooral cash — pin werkt soms'],
 '{"Maandag t/m donderdag":"Gesloten","Vrijdag":"07:00 – 14:00","Zaterdag":"07:00 – 14:00","Zondag":"07:00 – 14:00"}'::jsonb,
 '[{"section":"Wat je hier vindt (richtprijs)","items":[{"name":"Kilo tomaten","desc":"Spaans of Marokkaans","price":"1,50 – 2,00"},{"name":"Msemmen","desc":"Marokkaanse pannenkoek, vers","price":"1,00 – 1,50"},{"name":"Stuk brood (1 kg)","desc":"Versgebakken, nog warm","price":"1,80"},{"name":"Olijven (250g)","desc":"Tien soorten","price":"2,50"},{"name":"Hele kip","desc":"Geroosterd, met patatten","price":"8,00 – 10,00"},{"name":"Couscous-mix (kruiden)","desc":"Per zakje","price":"2,00"}]}]'::jsonb,
 NULL),

('biblio', 'Bibliotheek Anderlecht',
 50.8367, 4.3074,
 11, NULL, NULL,
 'Sint-Guidostraat 97, 1070 Anderlecht', NULL, NULL,
 0, '#134B8A', FALSE,
 ARRAY['Studeren','Gratis'],
 'Stille verdieping op 2. Gratis wifi, lange tafels, sluit om 19u door de week.',
 'Drie verdiepingen. Beneden = boeken, kinderhoek, soms lawaai. Verdieping 1 = computers en kranten. Verdieping 2 = stiltezone, lange houten tafels, raam op de straat. Lid worden is gratis voor wie in Brussel woont, anders 5 euro per jaar.',
 'Examenweek = vol. Kom voor 10u of zoek een plek op verdieping 1.',
 'Gratis lidkaart onder 26 jaar',
 ARRAY['Gratis lidmaatschap (-26 jaar)','Stille tafels op verdieping 2','Wifi: open netwerk, geen paswoord','24/7 boeken-inleverbus aan ingang'],
 ARRAY[]::text[],
 '{"Maandag":"Gesloten","Dinsdag":"12:30 – 19:00","Woensdag":"12:30 – 17:30","Donderdag":"15:00 – 19:00","Vrijdag":"12:30 – 17:30","Zaterdag":"10:00 – 14:00","Zondag":"Gesloten"}'::jsonb,
 NULL,
 '[{"name":"Studie-tafels","desc":"~30 plaatsen op verdieping 2"},{"name":"Computers","desc":"12 stuks, gratis met lidkaart"},{"name":"Wifi","desc":"Open, geen wachtwoord"},{"name":"Drukker","desc":"0,10 / pagina zwart-wit"},{"name":"Watercooler","desc":"Bij de ingang"}]'::jsonb),

('ramen', 'Takumi Tonkotsu Brussel',
 50.85016763409128, 4.3479046308424065,
 32, 8, 18,
 'Rue Sainte-Catherine 35, 1000 Brussel', NULL, NULL,
 2, '#7A1F2D', FALSE,
 ARRAY['Eten','Drinken'],
 'Ramen-zaakje. Lunchformule 12 euro, drukst rond 13u.',
 'Tien tafels, een open keuken, drie soorten ramen. De bouillon trekt 14 uur. Lunchformule (ramen + bijgerecht + drank) is 12 euro en is een van de beste deals in zuidelijk Brussel. Reserveren via Instagram-DM.',
 'Reserveer via @tonkotsubxl op Instagram. Walk-in voor 12u30 lukt meestal nog.',
 NULL,
 ARRAY['Lunchformule 12 euro','14u-bouillon — geen poederzooi','Vegan ramen op de kaart','Reserveren makkelijk via Insta'],
 ARRAY['Bancontact','Cash','Payconiq'],
 '{"Maandag":"12:00 – 22:00","Dinsdag":"12:00 – 22:00","Woensdag":"12:00 – 22:00","Donderdag":"12:00 – 22:00","Vrijdag":"12:00 – 22:30","Zaterdag":"12:00 – 22:30","Zondag":"12:00 – 21:30"}'::jsonb,
 '[{"section":"Ramen","items":[{"name":"Tonkotsu","desc":"Klassiek varkensbouillon, chashu, ei","price":"14,50"},{"name":"Shoyu kip","desc":"Sojabouillon, gerookte kip","price":"13,50"},{"name":"Vegan miso","desc":"Tofu, paddenstoelen, mais","price":"13,00"}]},{"section":"Bijgerechten","items":[{"name":"Gyoza (5)","desc":"Varken of groenten","price":"6,50"},{"name":"Edamame","desc":"Met zeezout","price":"4,00"},{"name":"Karaage","desc":"Gefrituurde kip, 6 stuks","price":"7,50"}]},{"section":"Lunchformule (12u – 14u30)","items":[{"name":"Ramen + edamame + thee","desc":"Alle ramen behalve tonkotsu","price":"12,00"}]}]'::jsonb,
 NULL),

('kaffabar', 'Kaffabar',
 50.842998, 4.345641,
 24, 9, 14,
 'Rouppeplein 1, 1000 Brussel', '+32498426684', NULL,
 2, '#8C5E3C', TRUE,
 ARRAY['Drinken','Studeren','Eten'],
 'Specialty coffee aan Rouppeplein. Veel laptops, goeie brunch en rustige sfeer.',
 'Kaffabar is een vaste waarde geworden voor studenten, freelancers en koffiemensen in Brussel. Binnen hangt een rustige Scandinavische vibe met veel natuurlijk licht, houten tafels en genoeg plaats om een paar uur te werken. Ze serveren specialty coffee, slow coffee en stevige brunches. Vooral in de voormiddag zie je hier veel laptops en mensen die rustig zitten te studeren of werken.',
 'Kom voor 11u als je rustig wilt studeren. Vrijdagmiddag zit het vaak helemaal vol.',
 'Gratis wifi + veel stopcontacten',
 ARRAY['Laptopvriendelijk buiten de lunchrush','Specialty coffee & slow coffee','Rustige sfeer om te studeren','Sterke brunch en homemade pastries','Terras op het Rouppeplein'],
 ARRAY['Cash','Bancontact','Payconiq'],
 '{"Maandag":"Gesloten","Dinsdag":"08:00 – 18:00","Woensdag":"08:00 – 18:00","Donderdag":"08:00 – 18:00","Vrijdag":"08:00 – 18:00","Zaterdag":"09:00 – 18:00","Zondag":"Gesloten"}'::jsonb,
 '[{"section":"Koffie","items":[{"name":"Espresso","desc":"House blend","price":"2,80"},{"name":"Flat White","desc":"Dubbele espresso met gestoomde melk","price":"4,20"},{"name":"Filter Coffee","desc":"V60 of Chemex","price":"4,50"},{"name":"Espresso Tonic","desc":"Iced coffee signature","price":"5,50"}]},{"section":"Ontbijt & lunch","items":[{"name":"Fresh Breakfast","desc":"Granola, yoghurt, fruit","price":"9,50"},{"name":"Rustic Breakfast","desc":"Brood, ei, kaas, confituur","price":"13,00"},{"name":"Lunch Tartines","desc":"Open sandwiches van de dag","price":"11,50"},{"name":"Cake van de dag","desc":"Homemade","price":"4,50"}]},{"section":"Extra","items":[{"name":"Chai Latte","desc":"Huisgemaakt","price":"4,80"},{"name":"Iced Tea","desc":"Vers gemaakt","price":"4,20"},{"name":"Espresso Martini","desc":"Vanaf de namiddag","price":"11,00"}]}]'::jsonb,
 NULL),

('izycoffee', 'Izy Coffee',
 50.848291, 4.347015,
 22, 8, 13,
 'Auguste Ortsstraat 9, 1000 Brussel', NULL, 'https://www.izycoffee.be/',
 2, '#D87B4A', TRUE,
 ARRAY['Drinken','Studeren','Eten'],
 'Grote koffiebar in centrum Brussel met veel plaats, lange openingsuren en laptopvriendelijke sfeer.',
 'Izy Coffee is één van de populairste study cafés in centrum Brussel. Door de lange openingsuren, vele zitplaatsen en snelle wifi zie je hier constant studenten en freelancers met laptops zitten. De sfeer is minder rustig dan specialty coffee bars zoals Kaffabar, maar ideaal als je lang wilt blijven werken of studeren. Ze serveren specialty coffee, iced drinks, matcha''s, vegan pastries en snelle ontbijt- of lunchopties.',
 'In de namiddag wordt het druk. Beste moment om rustig te studeren is voor 11u.',
 'Open tot laat + veel laptopplaatsen',
 ARRAY['Elke dag open tot 22u','Veel plaats voor laptops','Goede wifi en stopcontacten','Populaire study spot bij studenten','Snelle service voor tussen lessen'],
 ARRAY['Cash','Bancontact','Payconiq'],
 '{"Maandag":"07:00 – 22:00","Dinsdag":"07:00 – 22:00","Woensdag":"07:00 – 22:00","Donderdag":"07:00 – 22:00","Vrijdag":"07:00 – 22:00","Zaterdag":"07:00 – 22:00","Zondag":"07:00 – 22:00"}'::jsonb,
 '[{"section":"Koffie","items":[{"name":"Flat White","desc":"Dubbele espresso met melk","price":"4,40"},{"name":"Cappuccino","desc":"House blend espresso","price":"4,20"},{"name":"Iced Latte","desc":"Koude latte met ijs","price":"5,20"},{"name":"Espresso","desc":"Classic espresso shot","price":"2,90"}]},{"section":"Specials","items":[{"name":"Taro Latte","desc":"Populaire signature drink","price":"6,20"},{"name":"Pandan Matcha","desc":"Specialty matcha drink","price":"6,50"},{"name":"Speculicious Coffee","desc":"Signature winter coffee","price":"6,80"}]},{"section":"Food","items":[{"name":"Banana Bread","desc":"Homemade style cake","price":"4,80"},{"name":"Vegan Pastries","desc":"Wisselend aanbod","price":"4,50"},{"name":"Lunch Bun","desc":"Snelle lunchoptie","price":"7,50"}]}]'::jsonb,
 NULL),

('mokcoffee', 'MOK Coffee',
 50.853005, 4.343961,
 18, 7, 11,
 'Antoine Dansaertstraat 196, 1000 Brussel', '+32472058224', 'https://mokcoffee.be/',
 2, '#6B4C3B', TRUE,
 ARRAY['Drinken','Studeren','Eten'],
 'Bekende specialty coffee bar in de Dansaertwijk met rustige sfeer, top koffie en aparte laptopruimte.',
 'MOK Coffee is één van de bekendste specialty coffee bars van Brussel en wordt vaak genoemd als één van de beste koffieplekken van België. De zaak ligt in de Dansaertwijk en combineert minimalistische Scandinavische vibes met een heel rustige sfeer. Achteraan is er een aparte ruimte waar laptops welkom zijn, waardoor veel studenten en freelancers hier komen werken of studeren. Ze roasten hun eigen bonen en serveren filter coffee, espresso''s en seizoensgebonden brunchgerechten.',
 'Beste moment om rustig te studeren is in de voormiddag. In het weekend vaak erg druk.',
 'Laptopruimte achteraan + gratis wifi',
 ARRAY['Eén van de bekendste specialty coffee bars van Brussel','Aparte laptopruimte achteraan','House-roasted koffiebonen','Rustige Scandinavische sfeer','Populair bij studenten en freelancers'],
 ARRAY['Cash','Bancontact','Payconiq'],
 '{"Maandag":"08:00 – 18:00","Dinsdag":"08:00 – 18:00","Woensdag":"08:00 – 18:00","Donderdag":"08:00 – 18:00","Vrijdag":"08:00 – 18:00","Zaterdag":"10:00 – 18:00","Zondag":"10:00 – 18:00"}'::jsonb,
 '[{"section":"Koffie","items":[{"name":"Espresso","desc":"House roast espresso","price":"3,00"},{"name":"Flat White","desc":"Dubbele espresso met melk","price":"4,50"},{"name":"Filter Coffee","desc":"Single origin hand brew","price":"5,50"},{"name":"Nitro Coffee","desc":"Cold brew van het vat","price":"5,80"}]},{"section":"Ontbijt & lunch","items":[{"name":"Avocado Toast","desc":"Zuurdesembrood & kruiden","price":"13,50"},{"name":"Seasonal Brunch","desc":"Vegetarische lunch van het seizoen","price":"15,00"},{"name":"Banana Bread","desc":"Housemade banana bread","price":"4,80"},{"name":"Pastries","desc":"Dagelijks vers gebakken","price":"4,50"}]},{"section":"Extra","items":[{"name":"Matcha Latte","desc":"Ceremonial grade matcha","price":"5,50"},{"name":"Oat Milk Upgrade","desc":"Havermelk","price":"0,50"},{"name":"Coffee Beans","desc":"House roasted bonen","price":"Vanaf 16,00"}]}]'::jsonb,
 NULL),

('bouche', 'BOUCHE Specialty Coffee',
 50.841842, 4.359421,
 31, 11, 16,
 'Rue de Namur 4, 1000 Bruxelles', '+32493299802', NULL,
 2, '#B88A6A', TRUE,
 ARRAY['Drinken','Studeren','Eten'],
 'Specialty coffee vlak bij Naamsepoort met minimalistische inrichting en focus op filter coffee.',
 'BOUCHE is een specialty coffee bar in het centrum van Brussel met focus op high-end filter coffee en Europese specialty roasters. Online wordt de zaak vaak genoemd als één van de betere specialty coffee spots van Brussel. De ruimte heeft een minimalistische inrichting met grote stenen toog en rustige sfeer.',
 'In het weekend vaak erg druk volgens online reviews.',
 'Wifi beschikbaar',
 ARRAY['Bekend in de Brusselse specialty coffee scene','Focus op filter coffee en guest roasters','Minimalistisch interieur','Populair bij koffieliefhebbers','Goede locatie vlak bij centrum'],
 ARRAY['Bancontact','Cash'],
 '{"Maandag":"07:30 – 18:00","Dinsdag":"07:30 – 18:00","Woensdag":"07:30 – 18:00","Donderdag":"07:30 – 18:00","Vrijdag":"07:30 – 18:00","Zaterdag":"09:00 – 18:00","Zondag":"09:00 – 18:00"}'::jsonb,
 '[{"section":"Koffie","items":[{"name":"Espresso","desc":"Specialty espresso","price":"3,60"},{"name":"Milk Drinks","desc":"Latte / cappuccino","price":"4,60 – 5,20"},{"name":"Filter Coffee","desc":"Hand brew / batch brew","price":"—"}]},{"section":"Food","items":[{"name":"Pastries","desc":"Dagelijks aanbod pastries","price":"—"}]}]'::jsonb,
 NULL),

('taes', 'Tae''s sandwich',
 50.84772931448716, 4.361518750700231,
 26, 9, 14,
 'Rue du Gentilhomme 5, 1000 Bruxelles', '+32470866835', NULL,
 1, '#C96A3D', TRUE,
 ARRAY['Eten'],
 'Kleine sandwichzaak in centrum Brussel met rijk belegde broodjes en vriendelijke service.',
 'Tae''s sandwich is een kleine broodjeszaak in het centrum van Brussel. Online reviews vermelden vooral de vriendelijke service, verse producten en goed belegde sandwiches. De zaak lijkt vooral populair als snelle lunchplek.',
 'Vooral geschikt voor snelle lunch. Openingsuren lijken beperkt.',
 NULL,
 ARRAY['Verse ingrediënten volgens reviews','Goed belegde sandwiches','Kleine lokale zaak','Snelle lunchspot','Vriendelijke bediening'],
 ARRAY['Bancontact','Cash'],
 '{"Maandag":"11:15 – 15:30","Dinsdag":"11:15 – 15:30","Woensdag":"11:15 – 15:30","Donderdag":"Gesloten","Vrijdag":"Gesloten","Zaterdag":"Gesloten","Zondag":"Gesloten"}'::jsonb,
 '[{"section":"Broodjes","items":[{"name":"Chicken Sandwich","desc":"Kipbroodje","price":"—"},{"name":"Vegetarian Sandwich","desc":"Vegetarische optie beschikbaar","price":"—"},{"name":"Homemade Dessert","desc":"Huisgemaakt dessert volgens reviews","price":"—"}]}]'::jsonb,
 NULL),

('fritland', 'Fritland',
 50.84772289252201, 4.349910972230997,
 24, 8, 13,
 'Rue Henri Maus 19, 1000 Bruxelles', '+3225140627', 'http://fritlandbrussels.be/acceuil',
 1, '#D6A02C', TRUE,
 ARRAY['Eten','Drinken'],
 'Legendarische Brusselse frituur vlak bij de Beurs. Grote porties, lange wachtrijen en open tot laat.',
 'Fritland is één van de bekendste frituren van Brussel en bestaat sinds 1978. De zaak ligt vlak bij de Beurs en staat bekend om Belgische frieten, mitraillettes en late-night fastfood. Online reviews noemen vooral de grote porties, snelle service en centrale locatie. Het is vaak erg druk, zeker ''s avonds en in het weekend.',
 'Na 22u vaak erg druk. Veel mensen nemen hun frieten mee richting Grote Markt.',
 NULL,
 ARRAY['Bekende Brusselse frituur sinds 1978','Open tot laat in de nacht','Grote porties frieten','Vlak bij de Beurs','Populaire stop na het uitgaan'],
 ARRAY['Cash','Bancontact'],
 '{"Maandag":"11:00 – 01:00","Dinsdag":"11:00 – 01:00","Woensdag":"11:00 – 01:00","Donderdag":"11:00 – 03:00","Vrijdag":"11:00 – 03:00","Zaterdag":"11:00 – 03:00","Zondag":"11:00 – 01:00"}'::jsonb,
 '[{"section":"Frieten & snacks","items":[{"name":"Verse frieten","desc":"Belgische frieten","price":"3,50 – 5,50"},{"name":"Mitraillette","desc":"Broodje met frieten en snack","price":"8,00"},{"name":"Fricadelle","desc":"Klassieke Belgische snack","price":"3,00"},{"name":"Bicky Burger","desc":"Belgische fastfoodklassieker","price":"5,00"}]},{"section":"Sauzen","items":[{"name":"Andalouse","desc":"Pittige Belgische saus","price":"1,00"},{"name":"Samurai","desc":"Pikante mayo","price":"1,00"},{"name":"Tartaar","desc":"Klassieke frituursaus","price":"1,00"}]}]'::jsonb,
 NULL),

('biamara', 'Bia Mara',
 50.848637023774536, 4.350734920398734,
 24, 8, 13,
 'Rue du Marché aux Poulets 41, 1000 Bruxelles', '+3225020061', 'https://www.biamara.com/',
 2, '#2E5B7A', TRUE,
 ARRAY['Eten','Drinken'],
 'Populaire fish & chips spot vlak bij de Beurs met duurzame vis, homemade sauzen en creatieve smaken.',
 'Bia Mara is één van de bekendste fish & chips restaurants van Brussel. De zaak staat bekend om duurzame vissoorten, lichte krokante batter en homemade sauzen met internationale smaken. Online reviews noemen vooral de creatieve combinaties, grote porties en centrale locatie vlak bij de Beurs.',
 'Vrijdag- en zaterdagavond vaak lange wachtrij. Lunch is meestal rustiger.',
 NULL,
 ARRAY['Bekende fish & chips spot in Brussel','Duurzame vis en homemade sauzen','Creatieve smaken en toppings','Vlak bij de Beurs','Populair bij toeristen én locals'],
 ARRAY['Cash','Bancontact'],
 '{"Maandag":"12:00 – 14:00 / 18:00 – 21:00","Dinsdag":"12:00 – 14:00 / 18:00 – 21:00","Woensdag":"12:00 – 14:00 / 18:00 – 21:00","Donderdag":"12:00 – 14:00 / 18:00 – 21:00","Vrijdag":"12:00 – 14:00 / 18:00 – 22:00","Zaterdag":"12:00 – 22:00","Zondag":"12:00 – 15:00 / 18:00 – 21:00"}'::jsonb,
 '[{"section":"Fish & Chips","items":[{"name":"Classic Panko","desc":"Krokante vis met frieten","price":"13,00"},{"name":"Lemon & Basil Tempura","desc":"Tempura fish met frisse kruiden","price":"14,50"},{"name":"Indian Spiced Panko","desc":"Fish & chips met curry-lime saus","price":"14,50"}]},{"section":"Sides","items":[{"name":"Sweet Potato Fries","desc":"Zoete aardappelfrietjes","price":"4,00"},{"name":"Minty Mushy Peas","desc":"Klassieke mushy peas","price":"4,00"},{"name":"Vietnamese Salad","desc":"Frisse salade","price":"4,00"}]},{"section":"Sauzen","items":[{"name":"Garlic Truffle Sauce","desc":"Knoflook & truffel","price":"1,00"},{"name":"Jalapeño Lime Sauce","desc":"Pikant en fris","price":"1,00"},{"name":"Homemade Tartar","desc":"Huisgemaakte tartaar","price":"1,00"}]}]'::jsonb,
 NULL),

('casco', 'CASCO',
 50.84811173316971, 4.351288739388422,
 24, 8, 13,
 'Rue de la Bourse 42, 1000 Bruxelles', NULL, 'https://cafecasco.be/',
 2, '#8A4F3D', TRUE,
 ARRAY['Drinken','Eten','Chillen'],
 'Grote bar-brasserie aan de Beurs met cocktails, speciaalbier, terras en late-night sfeer.',
 'CASCO is een grote café-brasserie vlak bij de Beurs in Brussel. Overdag komen mensen hier voor koffie, lunch of een terras, terwijl het ''s avonds meer verandert in een levendige cocktailbar met muziek en DJ-sets. Online reviews noemen vooral de centrale locatie, het grote terras en de levendige sfeer.',
 'Vrijdag- en zaterdagavond erg druk. Terras is populair bij goed weer.',
 NULL,
 ARRAY['Groot terras aan de Beurs','Cocktails, bier en food op één plek','Open tot diep in de nacht','Vaak live DJ''s en muziek','Populaire afspreekplek in centrum Brussel'],
 ARRAY['Cash','Bancontact','Payconiq','Visa','Mastercard'],
 '{"Maandag":"11:00 – 01:30","Dinsdag":"11:00 – 01:30","Woensdag":"11:00 – 01:30","Donderdag":"11:00 – 01:30","Vrijdag":"11:00 – 03:30","Zaterdag":"11:00 – 03:30","Zondag":"11:00 – 01:30"}'::jsonb,
 '[{"section":"Drinks","items":[{"name":"Cocktails","desc":"Klassieke en signature cocktails","price":"10,00 – 14,00"},{"name":"Belgische bieren","desc":"Lokale en internationale selectie","price":"4,00 – 7,00"},{"name":"Koffie","desc":"Espresso, cappuccino, latte","price":"3,00 – 5,00"}]},{"section":"Food","items":[{"name":"Burgers","desc":"Classic burgers met frieten","price":"15,00 – 18,00"},{"name":"Croquettes","desc":"Kaas- of garnaalkroketten","price":"—"},{"name":"Fingerfood","desc":"Nachos, onion rings, snacks","price":"—"}]}]'::jsonb,
 NULL),

('gecko', 'Gecko Brunch & Cocktail Bar',
 50.848091838835856, 4.346728016400397,
 23, 8, 12,
 'Place Saint-Géry 16, 1000 Bruxelles', '+32485981088', 'https://m.facebook.com/Gecko-Brussels-165738870268888/',
 2, '#4E7C6D', TRUE,
 ARRAY['Drinken','Eten','Chillen'],
 'Populaire brunch- en cocktailbar op Sint-Goriksplein met groot terras en late openingsuren.',
 'Gecko is een brunch- en cocktailbar aan het Sint-Goriksplein in Brussel. Online reviews noemen vooral de gezellige sfeer, cocktails, brunchgerechten en het grote terras. De zaak ligt midden in één van de populairste uitgaansbuurten van Brussel en wordt vaak genoemd als afspreekplek voor drankjes of brunch.',
 'Vrijdag- en zaterdagavond meestal erg druk rond Sint-Goriksplein.',
 'Gratis wifi',
 ARRAY['Groot terras op Sint-Goriksplein','Cocktails en brunch op één plek','Open tot laat in het weekend','Centrale ligging in het centrum','Populair bij locals en toeristen'],
 ARRAY['Cash','Bancontact','Visa','Mastercard'],
 '{"Maandag":"08:00 – 23:00","Dinsdag":"08:00 – 23:00","Woensdag":"08:00 – 23:00","Donderdag":"08:00 – 03:00","Vrijdag":"08:00 – 03:00","Zaterdag":"08:00 – 03:00","Zondag":"08:00 – 23:00"}'::jsonb,
 '[{"section":"Brunch","items":[{"name":"Pancakes","desc":"Volgens reviews populair tijdens brunch","price":"—"},{"name":"Omelettes","desc":"Custom omelettes beschikbaar","price":"—"},{"name":"Toast & breakfast bowls","desc":"Ontbijt- en brunchopties","price":"—"}]},{"section":"Cocktails & drinks","items":[{"name":"Mojito","desc":"Vaak genoemd in reviews","price":"—"},{"name":"Classic Cocktails","desc":"Cocktailkaart met klassiekers","price":"—"},{"name":"Belgische bieren","desc":"Lokale bierselectie","price":"—"}]},{"section":"Food","items":[{"name":"Cheeseburger","desc":"Vermeld in online reviews","price":"—"},{"name":"Meatballs in tomato sauce","desc":"Kleine Belgische gerechten","price":"—"},{"name":"Croque Monsieur","desc":"Lunch/snack optie","price":"—"}]}]'::jsonb,
 NULL),

('ausoleil', 'Au Soleil.',
 50.84560886718737, 4.348052048168494,
 25, 8, 13,
 'Rue du Marché au Charbon 86, 1000 Bruxelles', '+3225123430', NULL,
 1, '#B46A43', TRUE,
 ARRAY['Drinken','Chillen','Studeren'],
 'Authentiek Brussels café in de Sint-Jacobswijk met groot terras, goedkope bieren en relaxte sfeer.',
 'Au Soleil is een klassiek Brussels café in de Sint-Jacobswijk, vlak bij het centrum. Het café bestaat al jaren en staat bekend om zijn groot terras, goedkope Belgische bieren en relaxte sfeer. Brusselse gidsen beschrijven het als één van de aangenaamste cafés van de buurt. Overdag zitten hier vaak mensen rustig koffie te drinken, lezen of werken, terwijl het ''s avonds levendiger wordt.',
 'Overdag relatief rustig. In de zomer zit het terras vaak helemaal vol.',
 'Wifi beschikbaar',
 ARRAY['Authentieke Brusselse café-sfeer','Groot terras bij goed weer','Goedkope Belgische bieren','Rustig overdag, levendig ''s avonds','Populair bij locals'],
 ARRAY['Cash','Bancontact'],
 '{"Maandag":"09:30 – 01:00","Dinsdag":"09:30 – 01:00","Woensdag":"09:30 – 01:00","Donderdag":"09:30 – 01:00","Vrijdag":"09:30 – 02:00","Zaterdag":"09:30 – 02:00","Zondag":"09:30 – 00:00"}'::jsonb,
 '[{"section":"Drinks","items":[{"name":"Belgische bieren","desc":"Chimay, Ciney, Westmalle","price":"3,50 – 6,00"},{"name":"Koffie","desc":"Espresso en klassieke koffie","price":"—"},{"name":"Cocktails","desc":"Klassieke cocktails beschikbaar","price":"—"}]},{"section":"Food","items":[{"name":"Croque Monsieur","desc":"Kleine cafégerechten","price":"—"},{"name":"Pasta bolo","desc":"Volgens Brusselse cafégidsen","price":"—"},{"name":"Soep","desc":"Kleine lunchoptie","price":"—"}]}]'::jsonb,
 NULL),

('mortsubite', 'À La Mort Subite',
 50.84862915991566, 4.356252575313457,
 23, 8, 12,
 'Rue Montagne aux Herbes Potagères 7, 1000 Bruxelles', '+3225131318', 'https://www.alamortsubite.com/',
 2, '#7B5A42', TRUE,
 ARRAY['Drinken','Chillen','Eten'],
 'Iconisch historisch Brussels café met art deco interieur, lambiekbier en oude Brusselse sfeer.',
 'À La Mort Subite is één van de bekendste historische cafés van Brussel. Het café bestaat sinds de jaren 1920 en staat bekend om zijn indrukwekkende art deco interieur, houten banken en traditionele lambiekbieren. De naam komt van een oud dobbelspel dat hier vroeger gespeeld werd. Online reviews en Brusselse gidsen beschrijven het café vaak als een plek die aanvoelt alsof je terug in de tijd stapt.',
 'Vaak erg druk door toeristen. Mooiste moment is in de late namiddag wanneer het iets rustiger is.',
 NULL,
 ARRAY['Historisch Brussels café sinds de jaren 1920','Iconisch art deco interieur','Bekend voor lambiek- en geuzebieren','Unieke oude Brusselse sfeer','Populaire stop voor toeristen én locals'],
 ARRAY['Cash','Bancontact','Visa','Mastercard'],
 '{"Maandag":"11:00 – 23:00","Dinsdag":"11:00 – 23:00","Woensdag":"11:00 – 23:00","Donderdag":"11:00 – 23:00","Vrijdag":"11:00 – 23:00","Zaterdag":"11:00 – 23:00","Zondag":"Gesloten"}'::jsonb,
 '[{"section":"Bieren","items":[{"name":"Mort Subite Lambic","desc":"Klassieke lambiek","price":"—"},{"name":"Kriek","desc":"Belgisch fruitbier","price":"—"},{"name":"Geuze","desc":"Traditioneel Brussels bier","price":"—"}]},{"section":"Food","items":[{"name":"Croques","desc":"Klassieke cafégerechten","price":"—"},{"name":"Toast & snacks","desc":"Kleine gerechten","price":"—"},{"name":"Desserts","desc":"Traditionele Brusselse desserts","price":"—"}]}]'::jsonb,
 NULL);
